# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          cache: packages
          before_install:
                - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
                - sudo apt-get --yes --force-yes update -qq
                - sudo add-apt-repository -y ppa:opencpu/jq
                - sudo apt-get --yes --force-yes update -qq
                - sudo apt-get install libjq-dev
                - sudo apt-get install --yes libudunits2-dev
                - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
          addons:
            chrome: stable
        - os: osx
          language: r
          osx_image: xcode9.2
          before_install:
                - brew update
                - brew upgrade
                - brew tap osgeo/osgeo4mac
                - brew outdated gdal
                - brew outdated gdal2
                - brew outdated geos

