# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: trusty

cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  - sudo apt-get install --yes libudunits2-dev
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
warnings_are_errors: false


