# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
    include:
        - os: linux
          sudo: false
          cache: packages
          dist: trusty
          addons:
            chrome: stable
        - os: osx
          language: r
          osx_image: xcode8
